version: "3.8"

services:

  client:
    build: client
    container_name: client
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: server
    container_name: server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27017